### ISSUE TITLE
issue when runnin with -d options

### ISSUE THREAD

**Issue by dummys** [conix-security/zer0m0n#1]
Hi when running cucko in debug mode I got the following;

2014-02-15 03:06:35,572 [lib.cuckoo.core.database] DEBUG: Database error fetching task: (OperationalError) no such column: tasks.analysis u'SELECT tasks.id AS tasks_id, tasks.target AS tasks_target, tasks.category AS tasks_category, tasks.timeout AS tasks_timeout, tasks.analysis AS tasks_analysis, tasks.priority AS tasks_priority, tasks.custom AS tasks_custom, tasks.machine AS tasks_machine, tasks.package AS tasks_package, tasks.options AS tasks_options, tasks.platform AS tasks_platform, tasks.memory AS tasks_memory, tasks.enforce_timeout AS tasks_enforce_timeout, tasks.clock AS tasks_clock, tasks.added_on AS tasks_added_on, tasks.started_on AS tasks_started_on, tasks.completed_on AS tasks_completed_on, tasks.status AS tasks_status, tasks.sample_id AS tasks_sample_id \nFROM tasks \nWHERE tasks.status = ? ORDER BY priority desc, added_on\n LIMIT ? OFFSET ?' ('pending', 1, 0)

And then the web interface is crashed...

Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, _args, *_kwargs)
  File "/opt/cuckoo/web/dashboard/views.py", line 55, in index
    tasks += db.list_tasks(offset=offset, status=TASK_REPORTED)
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'

Any idea ? When i remove the patch all is ok...
It's right after installing zer0m0n

**Comment by conix-security** [comment]
Hi Dummys !

We managed to find the bug while chatting on IRC. For other people who might encounter this issue, its occurs when you ran cuckoo at least 1 time before patching : the sqlite db is created, without the "tasks.analysis" field.

We will add a "ALTER TABLE" command on installation to modify existing sqlite db if any. For now, well, remove the db file before patching...

Thanks :]
